### ISSUE TITLE
pr2modules deprecation

### ISSUE THREAD

**Issue by scop** [uilibs/unifi-discovery#30]
Running current Home Assistant dev with deprecation warnings enabled yields a few of these warnings:

```
.../lib/python3.10/site-packages/pr2modules/__init__.py:12: DeprecationWarning: pr2modules namespace is deprecated, use pyroute2 instead
```

Looks like unifi-discovery is one of packages using `pr2modules`. See https://github.com/svinota/pyroute2/blob/c8aac9a721710bbb7cf6b9b8443d5f3c5132d1e2/pr2modules/__init__.py

HA dev installs pyroute2 0.7.3 at the moment.

**Comment by bdraco** [comment]
Ouch. Thats used in quite a few other places as well.  Thanks for the heads up

**Comment by bdraco** [comment]
I fixed this a while back but forgot to close
